/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as KanbanRouteImport } from './routes/kanban'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as CapturasRouteImport } from './routes/capturas'
import { Route as AutomacaoRouteImport } from './routes/automacao'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'

const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const KanbanRoute = KanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CapturasRoute = CapturasRouteImport.update({
  id: '/capturas',
  path: '/capturas',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomacaoRoute = AutomacaoRouteImport.update({
  id: '/automacao',
  path: '/automacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/analytics': typeof AnalyticsRoute
  '/automacao': typeof AutomacaoRoute
  '/capturas': typeof CapturasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/kanban': typeof KanbanRoute
  '/leads': typeof LeadsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/analytics': typeof AnalyticsRoute
  '/automacao': typeof AutomacaoRoute
  '/capturas': typeof CapturasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/kanban': typeof KanbanRoute
  '/leads': typeof LeadsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/analytics': typeof AnalyticsRoute
  '/automacao': typeof AutomacaoRoute
  '/capturas': typeof CapturasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/kanban': typeof KanbanRoute
  '/leads': typeof LeadsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/analytics'
    | '/automacao'
    | '/capturas'
    | '/configuracoes'
    | '/kanban'
    | '/leads'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/analytics'
    | '/automacao'
    | '/capturas'
    | '/configuracoes'
    | '/kanban'
    | '/leads'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/analytics'
    | '/automacao'
    | '/capturas'
    | '/configuracoes'
    | '/kanban'
    | '/leads'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AutomacaoRoute: typeof AutomacaoRoute
  CapturasRoute: typeof CapturasRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  KanbanRoute: typeof KanbanRoute
  LeadsRoute: typeof LeadsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanban': {
      id: '/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof KanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capturas': {
      id: '/capturas'
      path: '/capturas'
      fullPath: '/capturas'
      preLoaderRoute: typeof CapturasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automacao': {
      id: '/automacao'
      path: '/automacao'
      fullPath: '/automacao'
      preLoaderRoute: typeof AutomacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  AnalyticsRoute: AnalyticsRoute,
  AutomacaoRoute: AutomacaoRoute,
  CapturasRoute: CapturasRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  KanbanRoute: KanbanRoute,
  LeadsRoute: LeadsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
