/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as SenhasRouteImport } from './routes/senhas'
import { Route as ObjetivosRouteImport } from './routes/objetivos'
import { Route as MapasMentaisRouteImport } from './routes/mapas-mentais'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as KanbanRouteImport } from './routes/kanban'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as CapturasRouteImport } from './routes/capturas'
import { Route as AutomacaoRouteImport } from './routes/automacao'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MapasMentaisIndexRouteImport } from './routes/mapas-mentais.index'
import { Route as MapasMentaisBoardIdRouteImport } from './routes/mapas-mentais.$boardId'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const SenhasRoute = SenhasRouteImport.update({
  id: '/senhas',
  path: '/senhas',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjetivosRoute = ObjetivosRouteImport.update({
  id: '/objetivos',
  path: '/objetivos',
  getParentRoute: () => rootRouteImport,
} as any)
const MapasMentaisRoute = MapasMentaisRouteImport.update({
  id: '/mapas-mentais',
  path: '/mapas-mentais',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const KanbanRoute = KanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CapturasRoute = CapturasRouteImport.update({
  id: '/capturas',
  path: '/capturas',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomacaoRoute = AutomacaoRouteImport.update({
  id: '/automacao',
  path: '/automacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MapasMentaisIndexRoute = MapasMentaisIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MapasMentaisRoute,
} as any)
const MapasMentaisBoardIdRoute = MapasMentaisBoardIdRouteImport.update({
  id: '/$boardId',
  path: '/$boardId',
  getParentRoute: () => MapasMentaisRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/analytics': typeof AnalyticsRoute
  '/automacao': typeof AutomacaoRoute
  '/capturas': typeof CapturasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/kanban': typeof KanbanRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/mapas-mentais': typeof MapasMentaisRouteWithChildren
  '/objetivos': typeof ObjetivosRoute
  '/senhas': typeof SenhasRoute
  '/workspace': typeof WorkspaceRoute
  '/mapas-mentais/$boardId': typeof MapasMentaisBoardIdRoute
  '/mapas-mentais/': typeof MapasMentaisIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/analytics': typeof AnalyticsRoute
  '/automacao': typeof AutomacaoRoute
  '/capturas': typeof CapturasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/kanban': typeof KanbanRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/objetivos': typeof ObjetivosRoute
  '/senhas': typeof SenhasRoute
  '/workspace': typeof WorkspaceRoute
  '/mapas-mentais/$boardId': typeof MapasMentaisBoardIdRoute
  '/mapas-mentais': typeof MapasMentaisIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/analytics': typeof AnalyticsRoute
  '/automacao': typeof AutomacaoRoute
  '/capturas': typeof CapturasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/kanban': typeof KanbanRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/mapas-mentais': typeof MapasMentaisRouteWithChildren
  '/objetivos': typeof ObjetivosRoute
  '/senhas': typeof SenhasRoute
  '/workspace': typeof WorkspaceRoute
  '/mapas-mentais/$boardId': typeof MapasMentaisBoardIdRoute
  '/mapas-mentais/': typeof MapasMentaisIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/analytics'
    | '/automacao'
    | '/capturas'
    | '/configuracoes'
    | '/kanban'
    | '/leads'
    | '/login'
    | '/mapas-mentais'
    | '/objetivos'
    | '/senhas'
    | '/workspace'
    | '/mapas-mentais/$boardId'
    | '/mapas-mentais/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/analytics'
    | '/automacao'
    | '/capturas'
    | '/configuracoes'
    | '/kanban'
    | '/leads'
    | '/login'
    | '/objetivos'
    | '/senhas'
    | '/workspace'
    | '/mapas-mentais/$boardId'
    | '/mapas-mentais'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/analytics'
    | '/automacao'
    | '/capturas'
    | '/configuracoes'
    | '/kanban'
    | '/leads'
    | '/login'
    | '/mapas-mentais'
    | '/objetivos'
    | '/senhas'
    | '/workspace'
    | '/mapas-mentais/$boardId'
    | '/mapas-mentais/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AutomacaoRoute: typeof AutomacaoRoute
  CapturasRoute: typeof CapturasRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  KanbanRoute: typeof KanbanRoute
  LeadsRoute: typeof LeadsRoute
  LoginRoute: typeof LoginRoute
  MapasMentaisRoute: typeof MapasMentaisRouteWithChildren
  ObjetivosRoute: typeof ObjetivosRoute
  SenhasRoute: typeof SenhasRoute
  WorkspaceRoute: typeof WorkspaceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/senhas': {
      id: '/senhas'
      path: '/senhas'
      fullPath: '/senhas'
      preLoaderRoute: typeof SenhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objetivos': {
      id: '/objetivos'
      path: '/objetivos'
      fullPath: '/objetivos'
      preLoaderRoute: typeof ObjetivosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapas-mentais': {
      id: '/mapas-mentais'
      path: '/mapas-mentais'
      fullPath: '/mapas-mentais'
      preLoaderRoute: typeof MapasMentaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanban': {
      id: '/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof KanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capturas': {
      id: '/capturas'
      path: '/capturas'
      fullPath: '/capturas'
      preLoaderRoute: typeof CapturasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automacao': {
      id: '/automacao'
      path: '/automacao'
      fullPath: '/automacao'
      preLoaderRoute: typeof AutomacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapas-mentais/': {
      id: '/mapas-mentais/'
      path: '/'
      fullPath: '/mapas-mentais/'
      preLoaderRoute: typeof MapasMentaisIndexRouteImport
      parentRoute: typeof MapasMentaisRoute
    }
    '/mapas-mentais/$boardId': {
      id: '/mapas-mentais/$boardId'
      path: '/$boardId'
      fullPath: '/mapas-mentais/$boardId'
      preLoaderRoute: typeof MapasMentaisBoardIdRouteImport
      parentRoute: typeof MapasMentaisRoute
    }
  }
}

interface MapasMentaisRouteChildren {
  MapasMentaisBoardIdRoute: typeof MapasMentaisBoardIdRoute
  MapasMentaisIndexRoute: typeof MapasMentaisIndexRoute
}

const MapasMentaisRouteChildren: MapasMentaisRouteChildren = {
  MapasMentaisBoardIdRoute: MapasMentaisBoardIdRoute,
  MapasMentaisIndexRoute: MapasMentaisIndexRoute,
}

const MapasMentaisRouteWithChildren = MapasMentaisRoute._addFileChildren(
  MapasMentaisRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  AnalyticsRoute: AnalyticsRoute,
  AutomacaoRoute: AutomacaoRoute,
  CapturasRoute: CapturasRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  KanbanRoute: KanbanRoute,
  LeadsRoute: LeadsRoute,
  LoginRoute: LoginRoute,
  MapasMentaisRoute: MapasMentaisRouteWithChildren,
  ObjetivosRoute: ObjetivosRoute,
  SenhasRoute: SenhasRoute,
  WorkspaceRoute: WorkspaceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
